apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: generator
  name: dubizzle
spec:
  replicas: 4
  selector:
    matchLabels:
      run: generator
  template:
    metadata:
      labels:
        run: generator
    spec:
      containers:
      - image: nginx
        name: nginx
      - image: tocy/dubizzle-sre-tochukwu.nwoko:1.1
        name: dubizzle
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 8000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: generator
  name: dubizzle
spec:
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 80
  - name: port-2
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: generator
