---
- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest
  - name: Install a list of python packages
    apt:
      pkg:
      - python3 
      - python3-pip
  - name: install the package, force upgrade
    pip: 
      name: Django
      state: latest
  - name: Start Django Project
    shell: cd /var/www/ && django-admin startproject django_app
  - name: Start Migrate
    shell: cd /var/www/django_app  && python3 manage.py migrate
  - name: Create user
    shell: cd /var/www/django_app  && python3 manage.py createsuperuser
  - name: Add a line to a file if the file does not exist, without passing regexp
    lineinfile:
      path: /var/www/django_app/settings.py
      line: ALLOWED_HOSTS = ['0.0.0.0']
      create: yes
  - name: start django_app
    shell: cd /var/www/django_app python3 manage.py runserver 0.0.0.0:8080
    