# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4
image:
  repository: nginx
  repositoryb: tocy/dubizzle-sre-tochukwu.nwoko
  pullPolicy: IfNotPresent
  pullSecret:
  tag: 1.13.5-alpine
  tagb:  1.1
nameOverride: ""
fullnameOverride: ""
podSecurityContext: {}

service:
  type: ClusterIP
  port: 80
  portb: 8000